SysMap::value_type( "print", SysInfo( Arity( 1, true ), Arity( 0 ), sysRefPrint, "Prints any values in reading format" ) ),
SysMap::value_type( "println", SysInfo( Arity( 1, true ), Arity( 0 ), sysRefPrintln, "Prints any values in reading format and then adds a new line" ) ),
SysMap::value_type( "show", SysInfo( Arity( 1, true ), Arity( 0 ), sysRefShow, "Prints any values in summary format" ) ),
SysMap::value_type( "showln", SysInfo( Arity( 1, true ), Arity( 0 ), sysRefShowln, "Prints any values in summary format and then adds a new line" ) ),
