/******************************************************************************\
    Copyright (c) 2010 Stephen Leach. AppGinger is distributed under the terms 
    of the GNU General Public License. This file is part of AppGinger.

    AppGinger is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    AppGinger is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with AppGinger.  If not, see <http://www.gnu.org/licenses/>.
\******************************************************************************/

#ifndef KEYWORDS_HPP
#define KEYWORDS_HPP

#define KW_2_BANG					"!!"
#define KW_2_HAT					"^^"
#define KW_2_SEMICOLON		 		";;"
#define KW_ABS_AND					"&&"
#define KW_ABS_OR					"||"
#define KW_ADD						"+"
#define KW_ALSO 					"also"
#define KW_AND 						"and"
#define KW_APPEND					"++"
#define KW_APPEND_ALT				"<>"
#define KW_ARROW_LEFT				"<-"
#define KW_ARROW_RIGHT				"->"
#define KW_BANG						"!"
#define KW_BAR 						"|"
#define KW_BIND_LEFT				":="
#define KW_BIND_RIGHT				"=:"
#define KW_BRACE_CLOSE				"}"
#define KW_BRACE_OPEN 				"{"
#define KW_BY 						"by"
#define KW_CASE 					"case"
#define KW_CATCH 					"catch"
#define KW_COLON 					":"
#define KW_COMMA					","
#define KW_CROSS                    "&"
#define KW_DEFAULT 					"default"
#define KW_DEFINE 					"define"
#define KW_DIV						"/"
#define KW_DO 						"do"
#define KW_DOLLAR 					"$"
#define KW_ELSE 					"else"
#define KW_ELSEIF 					"elseif"
#define KW_ELSEUNLESS 				"elseunless"
#define KW_END_ELEMENT				"</>"
#define KW_ENDDEFINE 				"enddefine"
#define KW_ENDDO                    "enddo"
#define KW_ENDFOR 					"endfor"
#define KW_ENDIF					"endif"
#define KW_ENDLAMBDA	       		"endfn"
#define KW_ENDPACKAGE 				"endpackage"
#define KW_ENDRECORDCLASS           "endrecordclass"
#define KW_ENDSWITCH 				"endswitch"
#define KW_ENDTRANSACTION 			"endtransaction"
#define KW_ENDTRY 					"endtry"
#define KW_ENDUNLESS                "endunless"
#define KW_EQUAL 					"="
#define KW_EXPLODE					"..."
#define KW_FAT_BRACE_CLOSE			"%}"
#define KW_FAT_BRACE_OPEN 			"{%"
#define KW_FAT_BRACKET_CLOSE 		"%]"
#define KW_FAT_BRACKET_OPEN			"[%"
#define KW_FAT_PAREN_CLOSE			"%)"
#define KW_FAT_PAREN_OPEN			"(%"
#define KW_FIELD                    "field"
#define KW_FINALLY                  "finally"
#define KW_FN_ARROW					"=>>"
#define KW_FOR                      "for"
#define KW_FROM 					"from"
#define KW_FUNCTION 				"function"
#define KW_GT						">"
#define KW_GTE 						">="
#define KW_IDENTICAL				"=="
#define KW_IF 						"if"
#define KW_IMPORT 					"import"
#define KW_IN 						"in"
#define KW_INFIX_APPLY_1			"."
#define KW_INFIX_APPLY_2			"@"
#define KW_ISNT_ABSENT				"??"
#define KW_LAMBDA 					"fn"
#define KW_LIST_CLOSE				"]"
#define KW_LIST_OPEN				"["
#define KW_LT 						"<"
#define KW_LT_SLASH					"</"
#define KW_LTE 						"<="
#define KW_MAP_CLOSE				"}"
#define KW_MAP_OPEN					"{"
#define KW_MAPLET 					"=>"
#define KW_MAPLET_THIN				":-"
#define KW_MOD 						"mod"
#define KW_MUL 						"*"
#define KW_OR 						"or"
#define KW_PACKAGE 					"package"
#define KW_PANIC 					"!!!"
#define KW_PAREN_CLOSE				")"
#define KW_PAREN_OPEN				"("
#define KW_POW						"**"
#define KW_QUO 						"div"
#define KW_RECORDCLASS  			"recordclass"
#define KW_RETURN 					"return"
#define KW_SEMICOLON				";"
#define KW_SET_LEFT					"::="
#define KW_SET_RIGHT 				"=::"
#define KW_SLASH_GT 				"/>"
#define KW_SLOT 					"slot"
#define KW_SUB						"-"
#define KW_SWITCH 					"switch"
#define KW_SYSCALL					">->"
#define KW_THEN 					"then"
#define KW_THROW 					"throw"
#define KW_TO 						"to"
#define KW_TRANSACTION 				"transaction"
#define KW_TRAP						"?!"
#define KW_TRY 						"try"
#define KW_UNLESS 					"unless"
#define KW_UNTIL 					"until"
#define KW_VAL 						"val"
#define KW_VAR 						"var"
#define KW_WHERE                    "where"
#define KW_WHILE                    "while"
#define KW_WITH 					"with"
#define KW_ZIP                      "//"

#endif