#!/bin/sh
mkdir /tmp/rudecgi
cd /tmp/rudecgi
wget -q http://www.rudeserver.com/cgiparser/download/rudecgi-5.0.0.tar.gz
tar zxf rudecgi-5.0.0.tar.gz
cd rudecgi-5.0.0
./configure
make
sudo make install

